### ISSUE TITLE
request to join codecheckers

### ISSUE THREAD

**Issue by leipzig** [codecheckers/codecheckers#1]
Jeremy Leipzig
0000-0001-7224-9620
Bioinformatics

**Comment by nuest** [comment]
Welcome @leipzig ! (What an awesome handle, err, name by the way - Have you ever been to Leipzig?)

While I'm still setting up a proper process, would you be so kind to provide some contact information (institutional or personal website), since your ORCID also does not have that in an obvious way. 

Can you please also tell us what programming languages your are familiar with? Ideally every codechecker should be able to follow the instructions, but of course you can be more effective if you know the language.

Thanks!

**Comment by nuest** [comment]
I went ahead and used the information from your GitHub profile. Ping me or open a PR if you want to edit. Thanks.

**Comment by leipzig** [comment]
Thanks for adding me to Codecheckers. I am a PhD student at Drexel University in the College of Computer and Information Science. My email is simply my last name at gmail (never been there but maybe someday). I am interested in reproducing genomics and bioinformatics papers. In particular, those that would benefit from a refactor to enable "tests of robustness" (tool or parameter swaps). My dissertation will require this so I am motivated to contribute.

I have a good bit of experience in R, Python, and Java.
