### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by annloh** [codecheckers/codecheckers#13]
- Name: Anna Lohmann
- ORCID: https://orcid.org/0000-0002-4004-4265 
- Contact: https://annloh.github.io/
- Fields/domains of expertise
  - Psychology, psychometrics, SEM, network models, simulation, some epidemiology and biomedical statistics
- Programming language(s) and experience levels
  - R (advanced for a researcher; advanced beginner for a programmer)

------

How did you hear about CODECHECK?

ReproHack

What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.

All of the above. This should be the norm so I have to be part of the change.

How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?

I don't regard codechecking as any less important than peer-reviewing. If it is worth doing it is worth doing it right.

**Comment by nuest** [comment]
Hi Anna!

Thanks for your interest in becoming a codechecker! :heart:

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

We will get in touch when we have a paper matching your expertise. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-process). If you're engaged as reviewer or editor with a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:

Also, since you're already an expert in ReproHacking, maybe you'd be interested to collaborate on material for how to approach/conduct a reproduction and/or check? Drop me an email!
