### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by krassowski** [codecheckers/codecheckers#18]
Your data:

```csv
Michał Krassowski,@krassowski,0000-0002-9638-7785,see ORCID page,"bioinformatics, systems biology, omics integration, drug repurposing, women's health","Python (expert), R (intermediate), javascript/typescript (intermediate), C/C++ (a bit rusty)"
```

**How did you hear about CODECHECK?**

A link within an article within Software Sustainability Institute newsletter

**What is your motivation to contribute to CODECHECK?** E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc.**

Supporting reproducible research/open science

**How much time would you be able to spend on codechecking** (e.g., compared to time spend reviewing papers)?

I am happy to set aside up to 6 hours every other weekend.

**Comment by nuest** [comment]
Hi @krassowski !

Thanks for your interest in becoming a codechecker! :heart: And my sincere apologies for the delay in handling your registration.

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

I also used your current email, since your ORCID profile did not have one.

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-process). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:
