### ISSUE TITLE
Register as codechecker

### ISSUE THREAD

**Issue by sjvrijn** [codecheckers/codecheckers#20]
Your data:

```csv
Sander van Rijn,@sjvrijn,0000-0001-6159-041X,see ORCID page,"computer science: evolutionary algorithms, machine learning, (social) network analysis","Python (expert),C++ (basic), Matlab/Octave (basic)"
```

------

_How did you hear about CODECHECK?_

Don't remember for sure, but probably related to the Leiden ReproHack from november 2019

_What is your motivation to contribute to CODECHECK? E.g., improving coding skills, giving back to community, supporting reproducible research/open science, etc._

I want to contribute to (establishing) a culture of open and reproducible science

_How much time would you be able to spend on codechecking (e.g., compared to time spend reviewing papers)?_

At least ~2 (evening) hours per week on average I think, would probably prefer to do code checking over a paper review

**Comment by nuest** [comment]
Hi @sjvrijn !

Thanks for your interest in becoming a codechecker! :heart:

I invited you to [the team](https://github.com/orgs/codecheckers/teams/codecheckers) and added you to [the list](https://github.com/codecheckers/codecheckers/blob/master/codecheckers.csv). Welcome!

I added your current email, since your ORCID page did not have one.

We will get in touch when we have a paper matching your expertise, which strongly depends on the ongoing conversations with journals and publishers - we'll keep you posted. Until then, feel free to keep an eye open for interesting preprints in your domain, which you can introduce to a [community CODECHECK](https://codecheck.org.uk/guide/community-process). If you're engaged as reviewer, why not suggest a CODECHECK with your next review? If you are editor at a journal, we'd be happy to chat with you about establishing CODECHECKs there! :muscle:
